<?php

namespace MadForWebs\BookingBundle\Repository;

/**
 * BookingPassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingPassRepository extends \Doctrine\ORM\EntityRepository
{
}
