<?php

namespace MadForWebs\BookingBundle\Repository;

/**
 * BookingObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingObjectRepository extends \Doctrine\ORM\EntityRepository
{
}
