<?php

namespace MadForWebs\FinancialBundle\Repository;

/**
 * ExpenditureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenditureRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByFilters($filters)
    {
        $dateStart = null;
        $dateEnd = null;

        if(isset($filters['date_start'])){
            $dateStart = $filters['date_start'];
//            $dateStart = new \DateTime($date->format('Y')."/".$date->format('m')."/01");
        }

        if(isset($filters['date_end'])){
            $dateEnd = $filters['date_end'];
//            $dateEnd = new \DateTime($date->format('Y')."/".$date->format('m')."/01");
        }

        if($dateStart == null){
            if(isset($filters['date'])){
                $date = $filters['date'];
            }else{
                $date = new \DateTime();
            }

            $dateStart = new \DateTime($date->format('Y')."/".$date->format('m')."/01");
            $dateEnd = new \DateTime($dateStart->format('Y/m/d'));
            $dateEnd = $dateEnd->modify("last day of this month");
        }elseif ($dateEnd == null){
            $dateEnd = new \DateTime();
        }



        $em = $this->getEntityManager();
        $querySQL =
            ' SELECT expenditure FROM CoreBundle:Expenditure expenditure '.
            ' WHERE ';

        $querySQL .= ' (( expenditure.dateBuy >= :from '.
            ' AND expenditure.dateBuy <= :to) '.
            ' OR ( expenditure.dateBuy <= :from '.
            ' AND expenditure.dateBuy >= :from)) ';

        $query = $em->createQuery(
            $querySQL
        );
        $query
            ->setParameter('from', $dateStart)
            ->setParameter('to', $dateEnd);

        return $query->getResult();
    }
}
