<?php

namespace FinancialBundle\Repository;

/**
 * IncomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomeRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByMovement($params = array())
    {

        $query = $this->createQueryBuilder('income');
        $query->where('income.account = :account')->setParameter('account', $params['account']);
        $query->andWhere('income.accountDestiny is not NULL');

        return $query->getQuery()->getResult();
    }
}
